version: '3.8'

services:
  app:
    #construye la imagen basado en el dockerfile
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/usuarios
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret
    # Evitamos conflictos de volúmenes que sobrescriben app.jar
    # Si deseas usar montajes en desarrollo, comenta la siguiente línea
    # volumes:
    #   - .:/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: usuarios
    ports:
      - "3306:3306"
