version: '3.8'
services:
  app:
    # Construye la imagen usando el Dockerfile de este directorio
    build: .
    ports:
      - "8080:8080"
    # Sincroniza el código en caliente para desarrollo (opcional)
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      # Variables de conexión a la base de datos MySQL
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/usuarios
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret

  # Servicio adicional de base de datos MySQL
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: usuarios
    ports:
      - "3306:3306"
